pipeline {
    agent any
    tools{
        maven 'My-Maven3.9'
    }
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Load Script') {
            steps {
                script {
                    gv = load "script.groovy"
                }
            }
        }
        
        stage('Build jar') {
            steps {
                script {
                    gv.buildJar()
                }
            }
        }
        stage('Run Test') {
            steps {
                script {
                    gv.runTest()
                }
            }
        }

        stage('Build image') { 
            steps {
                script {
                    gv.buillImage
                }
            }
        }

        stage('Deployment') {
            steps {
                script {
                    gv.deployApp
                }
            }
        }
    }
}
